name: malaysia_data_platform
version: "1.0.0"
profile: malaysia_data_platform

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  malaysia_data_platform:
    staging:
      +materialized: view
      +schema: dbt_staging
    marts:
      +materialized: table
      +schema: dbt_marts

seeds:
  malaysia_data_platform:
    +schema: dbt_marts
